### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Coloradohusky** [Coloradohusky/TikUp#12]
Add information about the commands and stuff

**Comment by mdPlusPlus** [comment]
Is this tool even supposed to *download* TikTok videos? So far it tries to *upload* them to the internet archive no matter the arguments I choose.

**Comment by Coloradohusky** [comment]
The main focus of the program is uploading to the Internet Archive, adding a `--no-upload` switch defeats the whole purpose of this program, in my eyes - I built this program as sort of a [tubeup](https://github.com/bibanon/tubeup), but for TikTok videos (cause it didn't really work on TikToks)
