### ISSUE TITLE
Tiktoks sorted by username into folders

### ISSUE THREAD

**Issue by thismomentisbruh** [Coloradohusky/TikUp#15]
Hey, so glad this exists btw.  Could you add the ability to have the downloads sorted by username into their own separate folder?  Also the ability to have profile pictures downloaded as well would be nice.

**Comment by Coloradohusky** [comment]
Good idea, I'll make it `--sort` or something like that, I'll get to work on it ASAP!

**Comment by Coloradohusky** [comment]
Added in 2020.07.19! Use `--sort` to sort into folders, and make sure to use `--no-delete` if you want to keep the videos once they're uploaded to the Internet Archive!

**Comment by Coloradohusky** [comment]
Also, a note about `--sort` - it sorts it into folders named `tiktok-<username>`, as to not potentially conflict with the `tmp` folder

**Comment by mdPlusPlus** [comment]
Is this still part of TikUp? It doesn't show up anywhere in the code, only in the README.
