### ISSUE TITLE
Make InternetArchive Optional

### ISSUE THREAD

**Issue by DankMemeGuy** [Coloradohusky/TikUp#16]
I don't think IA should be a requirement since some of us have hundreds of terabytes at our disposal. 

Some videos are more sensitive than others and having that uploaded to IA would defeat the purpose of archiving them; I might want to archive my friends' stuff, but my friend's don't want their stuff online, nor do I. If someone else publishes it online, sure, but I don't want to yet this script in it's current state forces me to.

**Comment by Coloradohusky** [comment]
My apologies for the late reply - the reason I built this was to both download from Tiktok and upload to the IA - similar to Tubeup, which downloads from YouTube and uploads to the IA. In my opinion, adding an option that disables uploads would defeat the purpose of this program.

**Comment by upintheairsheep2** [comment]
So use another program
