### ISSUE TITLE
ImportError: No module named TikTokApi

### ISSUE THREAD

**Issue by dpliszka** [Coloradohusky/TikUp#17]
$ python tikup.py username
Traceback (most recent call last):
  File "tikup.py", line 1, in <module>
    from TikTokApi import TikTokApi
ImportError: No module named TikTokApi

**Comment by Coloradohusky** [comment]
Have you installed TikTokApi with `pip install tiktokapi`?

**Comment by Coloradohusky** [comment]
Also, the preferred way to use TikUp is by installing with `pip install tikup`, and then running `tikup username`, so that you don't have to type `python tikup.py` and can run it from anywhere

**Comment by dpliszka** [comment]
Hey,

When I tried running *pip install tiktokapi *I get:

Collecting TikTokApi
  Using cached
https://files.pythonhosted.org/packages/89/da/337ec849df4039d08a0b66320f30c3967da4a39a436da5eccfe9836ac548/TikTokApi-3.5.2.tar.gz
Collecting pyppeteer (from TikTokApi)
  Using cached
https://files.pythonhosted.org/packages/b0/16/a5e8d617994cac605f972523bb25f12e3ff9c30baee29b4a9c50467229d9/pyppeteer-0.0.25.tar.gz
pyppeteer requires Python '>=3.5' but the running Python is 2.7.17

And when I try pip install tikup I get:

Collecting tikup
  Could not find a version that satisfies the requirement tikup (from
versions: )
No matching distribution found for tikup

**Comment by dpliszka** [comment]
pip3 seemed to fix it
