### ISSUE TITLE
Downloaded videos do not play in VLC

### ISSUE THREAD

**Issue by mdPlusPlus** [Coloradohusky/TikUp#21]
I have some videos that I've downloaded with an older version a few of TikUp a few weeks/months ago that play just fine. If I try to play videos that I downloaded today with the current version of TikUp (2020.10.6.1), nothing happens.
No error message, jsut VLC opening and not playing the video or showing how long the playtime is.

Is this an issue with TikUp or am I just really dumb right now?

youtube-dl 2020.9.20
TikTokApi 3.5.5
VLC 3.0.11.1
Ubuntu 20.04

**Comment by Coloradohusky** [comment]
Can you send me the video file so I can have a look at it?

**Comment by mdPlusPlus** [comment]
Wow, you're fast. Sure, this is just an example, but it's the same on every file.

https://gofile.io/d/cO263n

**Comment by Coloradohusky** [comment]
It works with my VLC, so there must be an issue on your end

[Screenshot](https://ibb.co/z8XP03z)

As for the second issue, do the files still get downloaded and uploaded?

**Comment by Coloradohusky** [comment]
And yeah, those errors are normal, and TikUp deals with them, so all the videos are still downloaded correctly

**Comment by mdPlusPlus** [comment]
Oh wow, okay. Has TikTok changed their video codec in the last few weeks? Because like I said, the old ones are playing just fine.

    $ snap list vlc
    Name  Version                   Rev   Tracking     Publisher  Notes
    vlc   3.0.11.1-108-g7f58842ea4  1962  latest/beta  videolan✓  -

Guess I should not use the beta channel then.

Thanks for helping me out!

**Comment by mdPlusPlus** [comment]
On a separate note: `archive.txt` is staying empty when using `--use-download-archive`

**Comment by mdPlusPlus** [comment]
Regarding the empty `archive.txt`:

I figured out it is due to a unhandled exception in `getUsername(tiktokid)` and `getTikTokObject(tiktokId)` (well actually 

Traceback for reference:

    Traceback (most recent call last):
      File "/home/user/.local/bin/tikup", line 8, in <module>
        sys.exit(main())
      File "/home/user/.local/lib/python3.8/site-packages/tikup/tikup.py", line 221, in main
        tiktoks = downloadTikToks(username, tiktoks, file, downloadType)
      File "/home/user/.local/lib/python3.8/site-packages/tikup/tikup.py", line 150, in downloadTikToks
        username = getUsername(tiktok)
      File "/home/user/.local/lib/python3.8/site-packages/tikup/tikup.py", line 170, in getUsername
        thing = api.getTikTokById(tiktokId)
      File "/home/user/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 661, in getTikTokById
        return self.getData(b, proxy=proxy)
      File "/home/user/.local/lib/python3.8/site-packages/TikTokApi/tiktok.py", line 73, in getData
        query = {'verifyFp': b.verifyFp, 'did': b.did, '_signature': b.signature}
    AttributeError: 'browser' object has no attribute 'verifyFp'
