### ISSUE TITLE
What does "Exception: Only one TikTokApi object is allowed" mean?

### ISSUE THREAD

**Issue by nike34** [Coloradohusky/TikUp#23]
Im fairly new to python and programming in general so this might be a simple issue.
When I try to execute this command: tikup --liked (my username) I get this error in the end
What does it mean?

**Comment by Coloradohusky** [comment]
Ah yeah, so there was a big update with TikTokApi recently, so I'll have to update TikUp to deal with all that - in the meantime, use `pip install tiktokapi==3.6.3` to go back to a TikTokApi version that TikUp supports. I'll update TikUp sometime soon, but for now just do that, and let me know if you have any other issues!

Oh, and one more thing - if you're using `--liked`, you'll have to use `--limit` as well, as there was a TikTokApi bug with getting liked videos - try doing `--liked 100`, and if nothing happens, go down to `--liked 50` or whatever, and just keep going down until liked videos start getting downloaded

Feel free to ask if you have any questions!

**Comment by nike34** [comment]
That did the trick, thanks a lot!
Though it seems that some videos can't be downloaded? I'm gettin an "ERROR: unsupported url" in some videos. It doesn't really matter that much since I can just download it manually but it's still.

**Comment by Coloradohusky** [comment]
Oh yeah, that's normal, the program first tries to download with Youtube-DL, but if that fails, it then downloads with TikTokApi, so all the videos are still getting downloaded
