### ISSUE TITLE
Update to work with latest TikTokApi version

### ISSUE THREAD

**Issue by Coloradohusky** [Coloradohusky/TikUp#24]
Ok, so now that TikUp is officially broken and doesn't work with an older TikTokApi version, I'll get to work on updating it this weekend

**Comment by Coloradohusky** [comment]
Still haven't gotten it to work yet :(

**Comment by TrueObsidian** [comment]
I get this error TikTokApi.exceptions.TikTokCaptchaError: TikTok blocks this request displaying a Captcha
Tip: Consider using a proxy or a custom_verifyFp as method parameters

**Comment by Coloradohusky** [comment]
Fixed in 2020.12.26
