### ISSUE TITLE
Return videos within a "liked" range

### ISSUE THREAD

**Issue by oreillyalan** [Coloradohusky/TikUp#26]
For example, lets say I use #modernwarefare. Is it possible to return the videos for that hashtag that are within the "liked" range of say 100 - 50. So all #modernwarefare videos that have more than 50 likes but less than 100? Of all the api's for tiktok I have seen, I have never seen this capability!

**Comment by Coloradohusky** [comment]
This project isn't an API for tiktok - I'd recommend seeing if TikTok-API has that functionality (https://github.com/davidteather/TikTok-Api), but I don't think they do at the moment.
